
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('projects').del()
    .then(function () {
      // Inserts seed entries
      return knex('projects').insert([
        {id: 1, user_id: '105315951604146958822', title: 'project 1', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed.'},
        {id: 2, user_id: '105315951604146958823', title: 'project 2', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed.'},
        {id: 3, user_id: '105315951604146958824', title: 'project 3', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed.'},
        {id: 4, user_id: '105315951604146958825', title: 'project 4', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'},
        {id: 5, user_id: '105315951604146958826', title: 'project 5', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'},
        {id: 6, user_id: '105315951604146958827', title: 'project 6', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'},
        {id: 7, user_id: '105315951604146958828', title: 'project 7', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'},
        {id: 8, user_id: '105315951604146958829', title: 'project 8', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'},
        {id: 9, user_id: '105315951604146958821', title: 'project 9', about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac libero ullamcorper, tincidunt justo a, eleifend sem. Cras in commodo quam. Sed aliquam diam id tincidunt finibus. Proin vestibulum sit amet eros quis dignissim. Morbi in aliquam ligula. Sed gravida sagittis quam. Nunc vitae ornare libero. Sed ut euismod leo, sed mattis nunc. Sed quis nisi lorem. Proin ligula massa, lacinia eu faucibus vel, condimentum sed ligula. Maecenas quam lectus, tincidunt nec ante a, tempor sodales magna. Nam et quam cursus, porttitor turpis quis, vestibulum nibh. Donec id nisl ex. Vestibulum lacinia cursus nisi, non eleifend mi blandit in. Sed'}
      ]);
    });
};